################################
# Add the GENIE events
################################

## Replace this with the name of a GENIE rooTracker file
/generator/kinematics/rooTracker/input /storage/gpfs_data/neutrino/users/gsantoni/productions/SAND_2/SAND_2_0/sand-events.0.gtrac.root

## Use the T2K rooTracker input format.  This is directly supported by GENIE.
/generator/kinematics/set rooTracker

## Distribute the events based on the vertex in the rooTracker file.
/generator/position/set free

## The overlay file will have markers at the end of each event.  This tells
## edep-sim to generate vertices until it runs into an end-of-event marker.
## The value doesn't matter, but it needs to be larger than the maximum number
## of vertices in an event. 
#/generator/count/fixed/number 10000
#/generator/count/set fixed

## Distribute the event times based onn the time in the rooTracker file.
/generator/time/set free

#/generator/time/spill/start 0.0 ns
#/generator/time/spill/bunchCount 1000
#/generator/time/spill/bunchSep 10.0 ns
#/generator/time/spill/bunchLength 5.0 ns

## Make sure EDEPSIM updates the kinematics generator.
/generator/add

/edep/runId 0
/run/initialize
/run/beamOn 1151
